using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// 下载的arproduct material具体类型
/// </summary>
public enum ProductMaterialType 
{
     RESOURCE_TYPE_3D_MODEL = 3,
     RESOURCE_TYPE_ALG_FILE = 4,
     RESOURCE_TYPE_VIDEO_FILE = 5,
     RESOURCE_TYPE_QUAD_FILE = 6,
     RESOURCE_TYPE_TEXTURE_FILE = 7,
     RESOURCE_TYPE_RENDER_ENV = 8,
     RESOURCE_TYPE_RENDER_ENV_CONFIG = 9,
     RESOURCE_TYPE_UI_CONFIG = 10,
     RESOURCE_TYPE_2D_MARKER = 11,
     RESOURCE_TYPE_3D_ASSETBUNDLE_MODEL = 13,
     RESOURCE_TYPE_AUDIO_FILE = 14,
     RESOURCE_TYPE_GLOBALC_CONFIG_FILE = 15,
     RESOURCE_TYPE_INSIGHT_BUNDLE = 16,
     RESOURCE_TYPE_TEST_LUA_SCRIPT = 17,
     RESOURCE_TYPE_SCENE_FILE = 20,
     RESOURCE_TYPE_DYNAMIC_LOAD_FILE = 21,
     RESOURCE_TYPE_SCENE_CONFIG = 22
}
